version: 0.2

phases:
  install:
    commands:
      - echo command install
    finally:
      - echo command finally install

  pre_build:
    commands:
      - echo command pre_build
    finally:
      - echo command finally pre_build

  build:
    commands:
      - echo command build
      - mvn package
    finally:
      - echo command finally build

  post_build:
    commands:
      - echo command post_build
    finally:
      - echo command finally post_build

artifacts:
  files:
    - echo location artifacts
    - target/microservice-war-0.0.1-SNAPSHOT.war
