version: 0.2

run-as: Linux-user-name

env:
  shell: shell-tag

  parameter-store:

  exported-variables:
   - echo variable
   - echo variable
  secrets-manager:
    key: secret-id:json-key:version-stage:version-id
  git-credential-helper: no | yes

proxy:
  upload-artifacts: no | yes
  logs: no | yes

batch:
  fast-fail: false | true
    # build-list:
    # build-matrix:
    # build-graph:

phases:
  install:
    run-as: Linux-user-name
    on-failure: ABORT | CONTINUE
    runtime-versions:

    commands:
      - echo command
      - echo command
    finally:
      - echo command
      - echo command
  pre_build:
    run-as: Linux-user-name
    on-failure: ABORT | CONTINUE
    commands:
      - echo command
      - echo command
    finally:
      - echo command
      - echo command
  build:
    run-as: Linux-user-name
    on-failure: ABORT | CONTINUE
    commands:
      - echo command
      - echo command
    finally:
      - echo command
      - echo command
  post_build:
    run-as: Linux-user-name
    on-failure: ABORT | CONTINUE
    commands:
      - echo command
      - echo command
    finally:
      - echo command
      - echo command
reports:
  report-group-name-or-arn:
    files:
      - echo location
      - echo location
    base-directory: location
    discard-paths: no | yes
    file-format: report-format
artifacts:
  files:
    - echo location
    - echo location
  name: artifact-name
  discard-paths: no | yes
  base-directory: location
  exclude-paths: excluded paths
  enable-symlinks: no | yes
  s3-prefix: prefix

cache:
  paths:
    - echo path
    - echo path

#version: 0.2
#
#env:
#  variables:
#    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
#  parameter-store:
#
#phases:
#  install:
#    commands:
#      - echo Entered the install phase...-$(date +%Y-%m-%d)
#      - apt-get update -y
#      - apt-get install -y maven
#    finally:
#      - echo Ending the install phase...-$(date +%Y-%m-%d)
#  pre_build:
#    commands:
#      - echo Entered the pre_build phase...-$AWS_REGION
#    finally:
#      - echo Ending the pre_build phase...-$AWS_REGION
#  build:
#    commands:
#      - echo Entered the build phase...$AWS_REGION-$(date +%Y-%m-%d)
#      - echo Build started on `date`
#      - mvn clean install
#      - mvn prepare-package war:exploded
#    finally:
#      - echo Ending the build phase...$AWS_REGION-$(date +%Y-%m-%d)
#  post_build:
#    commands:
#      - echo Entered the post_build phase...
#      - echo Build completed on `date`
#    finally:
#      - echo Ending the post_build...$AWS_REGION-$(date +%Y-%m-%d)
##
###reports:
###  arn:aws:codebuild:your-region:your-aws-account-id:report-group/report-group-name-1:
###    files:
###      - "**/*"
###    base-directory: 'target/tests/reports'
###    discard-paths: no
###  reportGroupCucumberJson:
###    files:
###      - 'cucumber/target/cucumber-tests.xml'
###    discard-paths: yes
###    file-format: CUCUMBERJSON # default is JUNITXML
###artifacts:
###  files:
###    - target/microservice-war.war
###  discard-paths: yes
###  secondary-artifacts:
###    artifact1:
###      files:
###        - target/artifact-1.0.jar
###      discard-paths: yes
###    artifact2:
###      files:
###        - target/artifact-2.0.jar
###      discard-paths: yes
###cache:
###  paths:
###    - '/root/.m2/**/*'
###
