version: 0.2

phases:
  install:
    commands:
      - echo command install
    finally:
      - echo command finally install
  pre_build:
    commands:
      - echo command pre_build
    finally:
      - echo command finally pre_build
  build:
    commands:
      - echo command build
      - ls -la
      - mvn package
      - ls -la
      - ls -la target
    finally:
      - echo command finally build
  post_build:
    commands:
      - echo command post_build
    finally:
      - echo command finally post_build
reports:
  report-group-name-or-arn:
    files:
      - echo location reports

artifacts:
  files:
    - echo location artifacts
  name: artifact-name

cache:
  paths:
    - echo path cache

#version: 0.2
#
#env:
#  variables:
#    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
#  parameter-store:
#
#phases:
#  install:
#    commands:
#      - echo Entered the install phase...-$(date +%Y-%m-%d)
#      - apt-get update -y
#      - apt-get install -y maven
#    finally:
#      - echo Ending the install phase...-$(date +%Y-%m-%d)
#  pre_build:
#    commands:
#      - echo Entered the pre_build phase...-$AWS_REGION
#    finally:
#      - echo Ending the pre_build phase...-$AWS_REGION
#  build:
#    commands:
#      - echo Entered the build phase...$AWS_REGION-$(date +%Y-%m-%d)
#      - echo Build started on `date`
#      - mvn clean install
#      - mvn prepare-package war:exploded
#    finally:
#      - echo Ending the build phase...$AWS_REGION-$(date +%Y-%m-%d)
#  post_build:
#    commands:
#      - echo Entered the post_build phase...
#      - echo Build completed on `date`
#    finally:
#      - echo Ending the post_build...$AWS_REGION-$(date +%Y-%m-%d)
##
###reports:
###  arn:aws:codebuild:your-region:your-aws-account-id:report-group/report-group-name-1:
###    files:
###      - "**/*"
###    base-directory: 'target/tests/reports'
###    discard-paths: no
###  reportGroupCucumberJson:
###    files:
###      - 'cucumber/target/cucumber-tests.xml'
###    discard-paths: yes
###    file-format: CUCUMBERJSON # default is JUNITXML
###artifacts:
###  files:
###    - target/microservice-war.war
###  discard-paths: yes
###  secondary-artifacts:
###    artifact1:
###      files:
###        - target/artifact-1.0.jar
###      discard-paths: yes
###    artifact2:
###      files:
###        - target/artifact-2.0.jar
###      discard-paths: yes
###cache:
###  paths:
###    - '/root/.m2/**/*'
###
